name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  http: ^0.13.5  # For API requests
  flutter_polyline_points: ^2.0.0  # Replacement for polyline package
  url_launcher: ^6.1.11
  flutter_map_route: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true