name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.1.1
  flutter_map: ^5.0.0
  url_launcher: ^6.1.7
  latlong2: ^0.9.1
  http: ^1.3.0  # For API requests
  geolocator: ^9.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/autowala_logo.png